// Generates sw.js from what is actually in the repo. Run before serving or
// deploying (npm run serve does it; so does the Pages workflow).
//
// The app ships ~65MB of data: the kuromoji dictionary, six TTFs for the .docx
// embedding, the OCR models and the tesseract wasm. Precaching all of that
// would make installing the app a 65MB download, so only the shell is
// precached and the heavy files are kept as they are fetched. Whatever the
// teacher has actually used is then available offline.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const SKIP = new Set(['node_modules', '.git', '.github', 'tools', '_plans', 'docs']);
// precached: the shell, the code, and the small data the first screen needs
const CORE_DIRS = ['src', 'vendor', 'assets/icons', 'assets/data'];
const CORE_FILES = ['index.html', 'manifest.webmanifest'];
// fetched on demand and kept: too big to make everyone download up front, and
// the per-grade example corpus is only read when the picker asks for a grade
const LAZY_PREFIXES = [
  'assets/dict/', 'assets/fonts/', 'assets/tessdata/', 'vendor/tesseract/',
  'assets/data/lesson-kanji/',
];

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (SKIP.has(name) || name.startsWith('.')) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

const all = walk(root).map(p => relative(root, p).split('\\').join('/')).sort();
const core = [
  ...CORE_FILES,
  ...all.filter(f => CORE_DIRS.some(d => f.startsWith(d + '/')) && !LAZY_PREFIXES.some(p => f.startsWith(p))),
];
const missing = core.filter(f => !all.includes(f));
if (missing.length) throw new Error(`missing files: ${missing.join(', ')}`);
if (!core.some(f => f.startsWith('src/') && f.endsWith('.js'))) {
  throw new Error('no src/*.js in the core set, so a cached boot would not run');
}

// The cache name is a digest of every precached file, so a changed deploy makes
// a new cache and an update cycle; an identical rebuild does not.
const h = createHash('sha256');
for (const f of core) { h.update(f); h.update(readFileSync(join(root, f))); }
const version = h.digest('hex').slice(0, 12);

const sw = `// Generated by tools/gen-sw.mjs; do not edit.
const CACHE = 'ktm-${version}';
const CORE = ${JSON.stringify(core)};
// Google Fonts: the six preview faces. Small (subset woff2) and worth keeping,
// so the worksheet still previews in its real font offline.
const FONT_HOSTS = ['https://fonts.googleapis.com', 'https://fonts.gstatic.com'];

// Store a clean synthetic response: keeping the network headers on an already
// decoded body leaves a stale Content-Encoding that the browser then rejects.
async function sanitize(res) {
  const body = await res.blob();
  const headers = {};
  const ct = res.headers.get('Content-Type');
  if (ct) headers['Content-Type'] = ct;
  return new Response(body, { status: 200, headers });
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // The shell has to make it. A worker that installs during a bad window and
    // caches nothing would still report success and then delete the previous
    // cache on activate, taking offline support with it; throwing here discards
    // this worker instead and leaves the working one in charge.
    await Promise.all(CORE.map(async (url) => {
      const res = await fetch(url, { cache: 'no-cache' });
      if (!res.ok) throw new Error('core asset ' + url + ' -> ' + res.status);
      await cache.put(url, await sanitize(res));
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

// "update now" from the banner: the page that asks reloads on controllerchange
self.addEventListener('message', (event) => {
  if (event.data === 'ktm-skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin;
  if (!sameOrigin && !FONT_HOSTS.includes(url.origin)) return;

  if (req.mode === 'navigate') {
    // Cache-first on purpose: one cache holds an index.html together with the
    // exact scripts it names, so booting from it is always self-consistent. A
    // new deploy arrives through the worker's own update cycle.
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const shell = (await cache.match(req, { ignoreSearch: true })) || (await cache.match('index.html'));
      if (shell) return shell;
      try { return await fetch(req); } catch { return Response.error(); }
    })());
    return;
  }

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    const res = await fetch(req);
    // keep what came back, including the dictionary and fonts fetched on demand
    if (res.ok && (res.type === 'basic' || res.type === 'cors')) {
      await cache.put(req, await sanitize(res.clone()));
    }
    return res;
  })());
});
`;

writeFileSync(join(root, 'sw.js'), sw);
console.log(`sw.js: ${core.length} files precached, cache ktm-${version}`);
